# Refresh interval in minutes
interval: 60

# Text to add to the bot profile befor the list of subscribed servers
profile_prefix: "This bot mirrors trending posts from other servers into this server's local timeline. If you want another server added to the list ping @tante@tldr.nettime.org.

Currently mirroring trending posts from:
"

# profile fields to fill in
fields:
  code: https://github.com/tante/hype
  operator: "https://tldr.nettime.org/@tante"
  config: "https://github.com/tante/hypebot-config/"

# Define subscribed instances and
# their individual limit (top n trending posts)
# which is again limited by the API to max 20
subscribed_instances:
  chaos.social:
    limit: 10
  mastodon.social:
    limit: 10
  climatejustice.social:
    limit: 10
  fosstodon.org:
    limit: 10
  mastodon.art:
    limit: 10
  hachyderm.io:
    limit: 10
  scholar.social:
    limit: 10
  social.tchncs.de:
    limit: 10
